[package]
name = "datex-native-macros"
version = "0.0.3"
description = "DATEX Native Macros"
authors = [
    "Benedikt Strehle <benedikt@unyt.org>",
    "Jonas Strehle <jonas@unyt.org>",
    "Norbert Brzezinski <norbert@unyt.org>",
]
edition = "2024"
license-file = "../../LICENSE"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
datex-macro-utils = { version = "0.0.1" }
